### ISSUE TITLE
Maximum call stack exceeded

### ISSUE THREAD

**Issue by maciekpaprocki** [MadLittleMods/postcss-css-variables#135]
Seems like I am getting maximum call stack exceeded on postcss. 

used plugins with tailwind

```js
module.exports = {
    plugins: {
        'postcss-import': {},
        'tailwindcss/nesting': {},
        tailwindcss: {},
        autoprefixer: {},
        'postcss-sort-media-queries': {
            'sort': 'mobile-first'
        },

        'postcss-css-variables':{}
    },
}
```
error

```txt
RangeError: Maximum call stack size exceeded
    at Function.keys (<anonymous>)
    at shallowCloneNode (/Users/maciejpaprocki/Projects/bifl-nest/node_modules/postcss-css-variables/lib/shallow-clone-node.js:5:9)
    at /Users/maciejpaprocki/Projects/bifl-nest/node_modules/postcss-css-variables/lib/shallow-clone-node.js:36:13
    at Array.forEach (<anonymous>)
    at shallowCloneNode (/Users/maciejpaprocki/Projects/bifl-nest/node_modules/postcss-css-variables/lib/shallow-clone-node.js:5:19)
    at /Users/maciejpaprocki/Projects/bifl-nest/node_modules/postcss-css-variables/lib/shallow-clone-node.js:36:13
    at Array.forEach (<anonymous>)
    at shallowCloneNode (/Users/maciejpaprocki/Projects/bifl-nest/node_modules/postcss-css-variables/lib/shallow-clone-node.js:5:19)
  ```

**Comment by MadLittleMods** [comment]
@maciekpaprocki Which version of `postcss-css-variables` are you using?

Can you reproduce if you remove those other plugins?

Can you provide a minimal example of the input right before it goes into the `postcss-css-variables` that causes the error?

**Comment by searls** [comment]
FWIW, I'm seeing this happen whenever any nesting plugin is before this one in the plugin chain (using [tailwind/nesting](https://tailwindcss.com/docs/using-with-preprocessors#nesting))
